[2025-08-03T02:25:22.426+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-03T01:25:20.066207+00:00 [queued]>
[2025-08-03T02:25:22.429+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-03T01:25:20.066207+00:00 [queued]>
[2025-08-03T02:25:22.429+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T02:25:22.569+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): validate_weather_data> on 2025-08-03 01:25:20.066207+00:00
[2025-08-03T02:25:22.574+0000] {standard_task_runner.py:57} INFO - Started process 8358 to run task
[2025-08-03T02:25:22.577+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'nyc_weather_etl', 'validate_weather_data', 'scheduled__2025-08-03T01:25:20.066207+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/nyc_weather_etl.py', '--cfg-path', '/tmp/tmpzl8re22n']
[2025-08-03T02:25:22.579+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask validate_weather_data
[2025-08-03T02:25:22.613+0000] {task_command.py:415} INFO - Running <TaskInstance: nyc_weather_etl.validate_weather_data scheduled__2025-08-03T01:25:20.066207+00:00 [running]> on host 114f606b1815
[2025-08-03T02:25:22.645+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='nyc_weather_etl' AIRFLOW_CTX_TASK_ID='validate_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T01:25:20.066207+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T01:25:20.066207+00:00'
[2025-08-03T02:25:22.651+0000] {logging_mixin.py:151} INFO - Weather data validation passed. 24 records ready for processing.
[2025-08-03T02:25:22.656+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-08-03T02:25:22.660+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=nyc_weather_etl, task_id=validate_weather_data, execution_date=20250803T012520, start_date=20250803T022522, end_date=20250803T022522
[2025-08-03T02:25:22.675+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-08-03T02:25:22.684+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
