[2025-08-03T06:25:22.100+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-03T04:25:20.153064+00:00 [queued]>
[2025-08-03T06:25:22.108+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-03T04:25:20.153064+00:00 [queued]>
[2025-08-03T06:25:22.109+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2025-08-03T06:25:22.125+0000] {taskinstance.py:1380} INFO - Executing <Task(ExternalTaskSensor): wait_for_weather_data> on 2025-08-03 04:25:20.153064+00:00
[2025-08-03T06:25:22.129+0000] {standard_task_runner.py:57} INFO - Started process 25090 to run task
[2025-08-03T06:25:22.133+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'comprehensive_analytics_pipeline', 'wait_for_weather_data', 'scheduled__2025-08-03T04:25:20.153064+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/comprehensive_analytics_pipeline.py', '--cfg-path', '/tmp/tmp1n371kfb']
[2025-08-03T06:25:22.138+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask wait_for_weather_data
[2025-08-03T06:25:22.267+0000] {task_command.py:415} INFO - Running <TaskInstance: comprehensive_analytics_pipeline.wait_for_weather_data scheduled__2025-08-03T04:25:20.153064+00:00 [running]> on host 114f606b1815
[2025-08-03T06:25:22.416+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-engineering' AIRFLOW_CTX_DAG_ID='comprehensive_analytics_pipeline' AIRFLOW_CTX_TASK_ID='wait_for_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T04:25:20.153064+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T04:25:20.153064+00:00'
[2025-08-03T06:25:22.420+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:26:22.496+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:27:22.591+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:28:22.688+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:29:22.771+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:30:22.832+0000] {external_task.py:244} INFO - Poking for tasks ['spark_process_weather_to_iceberg'] in dag nyc_weather_etl on 2025-08-03T04:25:20.153064+00:00 ... 
[2025-08-03T06:30:22.857+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 274, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 300.43648984600077 seconds exceeds the specified timeout of 300.0.
[2025-08-03T06:30:22.873+0000] {taskinstance.py:1398} INFO - Immediate failure requested. Marking task as FAILED. dag_id=comprehensive_analytics_pipeline, task_id=wait_for_weather_data, execution_date=20250803T042520, start_date=20250803T062522, end_date=20250803T063022
[2025-08-03T06:30:22.883+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 59 for task wait_for_weather_data (Sensor has timed out; run duration of 300.43648984600077 seconds exceeds the specified timeout of 300.0.; 25090)
[2025-08-03T06:30:22.900+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-03T06:30:22.928+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
